### ISSUE TITLE
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by katyapavlenko** [darrylhodgins/typescript-memoize#17] opened 2019-12-03 12:35 UTC
```
WARNING in ./node_modules/typescript-memoize/dist/memoize-decorator.js 3:24-31
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```
angular 8.2.3
typescript 3.5.3

**Comment by katyapavlenko** [comment] 2019-12-03 12:46
Downgrading to 0.0.3 helps, but in further releases this should be fixed

**Comment by RyRy79261** [comment] 2020-01-23 10:13
Confirming issue on my side as well.

Sub dependency of `@connext/client` via typescript React

**Comment by lazarljubenovic** [comment] 2020-11-20 13:37
Does anyone know what's causing this? Since the repo looks abandoned, I'd like to at least create a fork.

**Comment by darrylhodgins** [comment] 2020-11-20 13:42
Yeah, I haven't had time to maintain this lately.  I'm open to pull requests or anyone else who'd like to help maintain it, though.

**Comment by darrylhodgins** [comment] 2020-11-20 14:41
On second thought, I decided to make a little bit of time this morning.  I've updated the dependencies and moved some other things around; would you be able to check whether this helps you, or provide a trivial test case that I can validate?

**Comment by lazarljubenovic** [comment] 2020-11-24 07:11
Hey @darrylhodgins, thanks for jumping in to address this. The new version `1.0.0-alpha.4` fixes the issue for me.

**Comment by darrylhodgins** [comment] 2020-11-24 14:13
I'm not sure if I'd call it "jumping"; I've been ignoring this project for a while and I forgot that I actually made it to be useful.  😃

Thanks for confirming.  I'll close this issue for now.

**Comment by lazarljubenovic** [comment] 2020-11-24 19:40
Well from my point of view it _was_ a jump in considering I only found the library this weekend :smile: (Also a friendly reminder that the issue is still open!)

**Comment by darrylhodgins** [comment] 2020-11-24 19:43
Yeah, I know… I was on the GitHub app this morning and it doesn't have the "Close" button for some reason :D

**Closed by darrylhodgins** 2020-11-24 19:43 UTC
